name: Tests

# CI workflow for Îµ-prolog
# Tests are defined in BOOK.org and executed via Makefile
# The test suite serves as both comprehensive documentation and functional testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs-version:
          - '30.2'
          - '29.4'
          - '28.2'
          - '27.2'
          - 'snapshot'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    - name: Show available test targets
      run: |
        make help

    - name: Check syntax and style
      run: |
        ls -la && make check

    - name: Run tests
      run: |
        ls -la && make test
